### ISSUE TITLE
AppendEquals problem with ' ( single quote / apostrophe)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [netTiers/netTiers#203] opened 2015-07-30 15:52 UTC
```
What steps will reproduce the problem?
1. No northwind built, but this should illustrate:

        [Test]
        public void DupPricingBOWithQuote()
        {
            string strTest = "Quotations's test";
            PricingBo testBO = new PricingBo();
            testBO.PricingBoName = strTest;
            testBO.PricingBodllName = strTest;
            testBO.PricingBoClassName = strTest;
            testBO.PricingBoStatus = 1;

            DataRepository.PricingBoProvider.Insert(testBO);

            PricingBoQuery query = new PricingBoQuery();
            query.AppendEquals(PricingBoColumn.PricingBoName,
testBO.PricingBoName.ToString());
            TList<paraDIAM.Entities.PricingBo> entities =
DataRepository.Provider.PricingBoProvider.Find(query.GetParameters());
            if (entities.Count == 0)
            {
                Assert.Fail(" count should have been greater then 0 ");
            }
        }


What is the expected output? What do you see instead?
I expect to see Find return a row.

What version of .netTiers and CodeSmith are you using?

CS = 4.0
NetTiers both nettiers-fx2.2-20080221-rev705 and 
nettiers-2.3-r804 exhibit this problem.

Please provide any additional information below.

I believe it's escaping the ' so it becomes '', passing this to the dynamic
query (read for procedures.xml), but it should NOT be escaped.  The quick
and dirty fix I came up with was:

XXX.Data\Bases\EntityProviderBaseCore.Generated.cs

        public virtual TList<Entity> Find(TransactionManager transactionManager,
IFilterParameterCollection parameters, string orderBy)
        {
            int count = 0;

            // sloppy -undo encode.
            for (int ii = 0; ii < parameters.GetParameters().Count; ii++)
            {
                parameters.GetParameters()[ii].Value =
parameters.GetParameters()[ii].Value.Replace("''", "'");
            }

            return Find(transactionManager, parameters, orderBy, 0, int.MaxValue,
out count);
        }

Once I do this, the Find returns a row as I expect.
```

Original issue reported on code.google.com by `mgran...@gmail.com` on 23 Apr 2009 at 4:33

**Comment by gregpakes** [comment] 2019-07-24 23:26
We have encountered this issue.  The proposed patch is not applied to the source here.  

Should it be?

**Comment by jeremeguenther** [comment] 2019-07-24 23:40
I closed this because it appeared that someone had already concluded the issue.  If this is still a problem, then we need to dig into it.

I would be very hesitant to apply the patch listed here because it is clearly a sql string escape.  Generally escaping ' is a very good idea for sql to prevent injection attacks.

Is it double escaping for you?

There are a few methods that do not escape the values like Contains and NotContains.  I would have to look at the generated dynamic sql for these various methods to try and figure out what the purpose of that escape was initially, and what the security impact of removing it would be.

**Comment by gregpakes** [comment] 2019-07-24 23:42
Thanks for the reply.

The issue is that the SQL is executed with parameters.  Therefore the escaping is not necessary.  

I am confused though because we have been using nettiers for 10+ years and I am baffled that we have not come across this before.

**Comment by jeremeguenther** [comment] 2019-07-24 23:50
I use primarily methods, which is probably why I have not seen it yet.  Looking at the blame, this file hasn't changed since 2008.

Not all values are parameterized unfortunately.  The fix probably needs to go through and turn this off for those that do parameterize, but leave it for those that do not.

**Comment by gregpakes** [comment] 2019-07-25 00:00
So I understand why the encode is required for the `SqlStringBuilder`, but I do not see why it is used in the `ParameterizedSqlFilterBuilder<EntityColumn>`.  I suspect that removing the encode from there, or amending it to not double quote would be the better solution.

**Comment by jeremeguenther** [comment] 2019-07-25 00:12
I'll add it to my backlog to look at.  If you have time, you can also submit a pull request for it.

The most important thing will be to build test cases for queries using IN, LIKE and NOTLIKE and make sure they still escape the values.

**Comment by gregpakes** [comment] 2019-07-25 00:15
Yep - I'll see if I get time.  I think this comment gives the issue away.

```
/// <summary>
/// Gets an encoded list of values for use with an IN clause.
/// </summary>
/// <param name="values">String Array with the in parameters</param>
/// <param name="encode">tells whether or not to enclose the parameters with ' and to replace ' with '' within the parameters.</param> <--- HERE
/// <returns></returns>
public virtual String GetInQueryValues(string[] values, bool encode)
{
    string inQuery = string.Empty;
     inQuery = SqlUtil.Encode(values, encode);
     return inQuery;
}
```

I think the surround bool is supposed to surround and perform the double quote escaping.  Instead it just surrounds and the double quote escaping is always performed.  Should be a fairly easy fix.

**Comment by gregpakes** [comment] 2019-07-25 06:50
I have created a PR which shows how I have resolved this in our codebase.

**Comment by jeremeguenther** [comment] 2019-07-25 14:29
Thanks for the pull request @gregpakes .  I am pretty slammed this week, so I think it will be a month or two before I have time to write all the tests required for injection testing in that area.

Something that will have to be modified is the use of string interpolation.  It was not introduced until c# 6 and nettiers supports versions older than that.

**Comment by jeremeguenther** [comment] 2019-07-31 01:49
I am doing a deep dive on this portion of the code, there are definitely some things that need to be cleaned up a bit.

The proposed solution here seems to work as long as you are using the ParameterizedSqlFilterBuilder class.  If  someone tries to use either SqlFilterBuilder or SqlStringBuilder by themselves due to a data access layer that does not support parameterization or for some other reason, then that solution would open them up to injection attacks.

I think your first idea of removing the encode method from the override methods in the ParameterizedSqlFilterBuilder class is the better one.

**Comment by jeremeguenther** [comment] 2019-08-22 01:03
An update on this issue.  I have the tests written, and the fix in place.  It is going off to my testing team, and then through a production burn-in next.

**Comment by jeremeguenther** [comment] 2019-09-07 00:47
I just submitted a pull request fixing this using your first idea @gregpakes of removing the encode method from the override methods, but leaving it in place for the base methods.

**Closed** 2019-09-10 15:09 UTC
Labels: Platform-SQL, Priority-Medium, Type-Defect, auto-migrated
